"""empty message

Revision ID: 494a25e4181d
Revises: 19171e7314e5
Create Date: 2022-07-07 00:31:40.194255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494a25e4181d'
down_revision = '19171e7314e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('title2', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('title2', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test2')
    op.drop_table('test')
    # ### end Alembic commands ###
