"""empty message

Revision ID: 662db11c8fe8
Revises: 1958a7469946
Create Date: 2022-07-11 00:58:11.385720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662db11c8fe8'
down_revision = '1958a7469946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('photo_1', sa.String(), nullable=True),
    sa.Column('photo_2', sa.String(length=50), nullable=True),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('stuff_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stuff_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
